### ISSUE TITLE
UX improvement suggestions

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-engine-ui#240]
1. Since the `Track` and `Type` are not editable, we can show them as tags instead of showing the disabled fields to save some space.

<img width="1502" alt="Screenshot 2020-05-05 at 2 48 37 PM" src="https://user-images.githubusercontent.com/4612921/81063223-1a1abd80-8ee0-11ea-8106-721c6d64d344.png">

2. Use `Community` review as the default instead of `Internal`
3. Using the `http://api.topcoder-dev.com/v5/challenge-timelines` endpoint, you can find the default `timelineTemplateId` to use based on the selected `typeId`.
4. Add a `Add private specification` checkbox to enable the `Private specification` editor. In many cases, this won't be needed so it shouldn't take space on the screen.
5. If the current logged in user has a copilot role on the project, select himself as the default copilot.
6. In the challenge listings, clicking on a challenge should open the `Edit` page and the current `Edit` link should change to `View` and that should link to the community app. As a copilot, being in the challenge editor, most likely I'd want to edit a challenge if I open it from this app. If feels more natural to click the challenge name but that's currently redirecting me to the challenge details page (community-app) which is frustrating.

Those are small details that will make the challenge creation process a bit easier/faster.

cc @rootelement @jmgasper

**Comment by jmgasper** [comment]
@rootelement / @ThomasKranitsas :

* I had brought up issue 1 in Slack yesterday.  I'll implement that
* Can I get confirmation that community should be the default review type?
* We can do the default timeline template ID
* Do we want to make private specification an optional / hidden field?  This is the first I've heard about this.
* We can default copilot
* Flipping the edit / view stuff makes sense, will log it.

**Comment by jmgasper** [comment]
Logged most of these separately.  I'm not going to default the timelineTemplateId or copilot currently, just to keep things simple while we work through the existing defects.
