### ISSUE TITLE
Error message seen while viewing challenge details.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/challenge-engine-ui#287]
**Describe the bug**

**To Reproduce / Actual Behavior**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

[Bug 1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599506/Bug.1.zip)

**Comment by vikasrohit** [comment]
Closing the issue as I don't find sufficient details to reproduce and verify.
