### ISSUE TITLE
List of Tags dropdown  is having repeated values in edit challenge page

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/challenge-engine-ui#291]
**Describe the bug**
the list of tags must be unique but same tags are present multiple times

**To Reproduce / Actual Behavior**
1.Open https://challenges.topcoder-dev.com/
2.Login with jcori
2.Click on "Another Test Project" from left side panel
3.Click on "Studio other challenge from the list"
4.Observe the Tags dropdown and its values

**Expected behavior**
All values should be unique and distinct

**Screenshots**
![Screenshot (182)](https://user-images.githubusercontent.com/29044523/81413832-bb657600-9163-11ea-89be-c88e3c0c5b3a.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Chrome 
 - Version 81.0.4044.129

**Comment by jmgasper** [comment]
Not a bug, just a data problem.  The app is functioning correctly.
