### ISSUE TITLE
User is able to delete all the phase (like Registration,appeals, submission etc) in challenge schedule

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#304]
**Describe the bug**
User is able to delete all the phase (like Registration,appeals, submission etc) in challenge schedule

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com and login as jcori / appirio123
2. Click on Another test project
3. Click on Launch new
4. Now add all the details
5. Now click on edit button in challenge schedule (heading)
6. Now observe user is able to delete the all the phases except review and also able to launch the challenge

**Expected behavior**
User should not able to delete all the phases because if there is no phase how he will review

**Screenshots**

[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599517/video.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
This isn't necessarily a bug.
