### ISSUE TITLE
Challenge schedule is showing incorrect End timelines

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/challenge-engine-ui#310]
**Describe the bug**
Challenge schedule is showing incorrect End timelines

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com and login as jcori / appirio123
2. Click on a Project and click on Launch New
3. Enter all the mandatory details
4. Click on Create Challenge
5. Select the Timeline template as Standard Code
6. Click on Edit and Observe the end dates for each phase

**Expected behavior**
End timelines should reflect be as per the timeline template.
**Screenshots**
PFA
**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version 81.0.4044.138

**Additional context**
[Bug_Video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599516/Bug_Video.zip)

**Comment by jmgasper** [comment]
This should have been logged with clear screenshots, not a long video that makes it very difficult to understand the problem.  Rejecting this because the logged issue isn't clear enough.
