### ISSUE TITLE
No texts limit in the Challenge name

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/challenge-engine-ui#314]
**Describe the bug**
There is no text limit in the challenge name input

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com/'
2. Log in 'Ghostar / appirio123'
3. On the "Active" challenges, click the first challenge "https://challenges.topcoder-dev.com/projects/null/challenges/34c5d4d5-13fb-49c1-9b0a-548da63ad5ec/edit"
4. Input text in the "Challenge name" textbox
5. Observe the error

**Expected behavior**
There should be a text limit for the challenge name of the  challenge top title

**Screenshots**
[textlimit.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599422/textlimit.zip)

**Desktop :**
 - OS: (Official Build) Built on Ubuntu , running on Ubuntu 16.04 
 - Browser: Chrome
 - Version: 81.0.4044.122
**Additional context**
The error happens to all the pages

**Comment by jmgasper** [comment]
There needs to be clear screenshots here - a video is unnecessary and makes it difficult to fully understand the issue.
