### ISSUE TITLE
There is no delete icon the first challenge prize

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/challenge-engine-ui#321]
**Describe the bug**
There is no delete icon in the Prize 1 of the challenge

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com/'
2. Log in 'Ghostar / appirio123'
3. On the "Active" challenges, click the first challenge "https://challenges.topcoder-dev.com/projects/null/challenges/34c5d4d5-13fb-49c1-9b0a-548da63ad5ec/edit"
4. Scroll below in the challenge details to the challenge prizes
5. Observe the prizes delete icon

**Expected behavior**
There should be an option to delete icon the Prize 1, which can display an error if the command is issued

**Screenshots or Video**
![delete](https://user-images.githubusercontent.com/37167721/81411951-c3192080-914b-11ea-83b3-8041d2d048e1.jpg)

**Desktop :**
  - OS: (Official Build) Built on Ubuntu , running on Ubuntu 16.04 
 - Browser: Chrome
 - Version: 81.0.4044.122

**Additional context**
The error appears in all the challenges edit page

**Comment by jmgasper** [comment]
Not a bug
