### ISSUE TITLE
prop type error from the API appears in the console

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/challenge-engine-ui#327]
**Describe the bug**
The error appears in the console after the pull request fails to get the prop type

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com/'
2. Log in 'Ghostar / appirio123'
3. Open the console and observe the prop type error

**Expected behavior**
There should be no error in the console when requesting data from the API, to access the prop types

**Screenshots**
[properror.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599077/properror.zip)

**Desktop :**
 - OS: (Official Build) Built on Ubuntu , running on Ubuntu 16.04 
 - Browser: Chrome
 - Version: 81.0.4044.122

**Additional context**
The error appears just after login the application

**Comment by jmgasper** [comment]
Not a security problem.
