### ISSUE TITLE
Unable to edit the challenge schedule

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/challenge-engine-ui#333]
**Describe the bug**
Unable to edit the challenge schedule

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com and login as jcori / appirio123
2. Click on a Project and click on Launch New
3. Enter all the mandatory details
4. Click on Create Challenge
5. Select the Timeline template as Standard Code
6. Click on Edit and observe the phases
7. Select the Timeline template again as Standard Code and click on Edit
8. Observe that schedule is unavailable to edit

**Expected behavior**
Challenge schedule should be available for edit as per the timeline template.
**Screenshots**
PFA
**Desktop:**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version 81.0.4044.138

**Additional context**
[Bug_Video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599527/Bug_Video.zip)

**Comment by jmgasper** [comment]
Not enough details here to work with.  There's obviously a problem on the page, but details would have been shown in the JS console window that weren't part of the logged ticket.
