### ISSUE TITLE
"No result seen when user clicks on ""Active Challenges""

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/challenge-engine-ui#341]
**Describe the bug**

**To Reproduce / Actual Behavior**

1. Go to url ""https://challenges.topcoder-dev.com/"" 
2. Log in as Ghostar with valid credentials.
3. Click on ""Active Challenges"" on the left navigation panel.
4. Observe. 

**Expected behavior**
User should not be able to click if no result is seen.

**Actual Result:**
User is able to click but no result is seen.

**Screenshots**
[Bug 2.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599536/Bug.2.zip)

**Desktop (please complete the following information):**
 OS: Windows 10
Browser: Chrome
Version 81.0.4044.138"

**Additional context**

**Comment by jmgasper** [comment]
Not detailed enough.
