### ISSUE TITLE
{Edit Challenge} Public specification: Select few lines and click on numbering won't display the incremental numbers

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#377]
https://monosnap.com/file/rZjxoRaOl0zH4IK8orC7UkvxVxcvyV

**URL:**
https://challenges.topcoder-dev.com/projects/9058/challenges/f0b20da3-69d8-4d02-a4ad-1f7db1fb8fb5/edit

**Reproduction Steps:**

1. Open the application and Login as a valid user (jcori)
2. Click on a Challenge (It will open the Edit Challenge)
3. Go to 'Public specification'
4. make few rows and select all rows
5. Click on Numbering button from the editor

**Actual Result:** 

- Public specification: Select few lines and click on numbering won't display the incremental numbers

**Expected Result:** 

- Should mark the list as 1, 2, 3, 4 etc

**Device/OS:** 

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 10 64bit (1909, 18363.815)

**Browser Information:** 

- **Browser(s):** Google Chrome 81.0.4044.138

**Comment by codejamtc** [comment]
Adding a Quote is not working also:

https://monosnap.com/file/LcygJw212bbMkXLI8qE2lU8sKxP75A

**Comment by jmgasper** [comment]
This is how most markdown editors work.  Not a bug.
