### ISSUE TITLE
Unable to Search challenges  starting with []

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#397]
**Describe the bug**
Unable to search challenges starting with []

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com'
2. Click on Search
3. Search project [F2F].'

Actual Result :
Unable to search based on F2F
**Expected behavior**
Should be able to search based on challenges [F2F]

**Screenshots**
![image](https://user-images.githubusercontent.com/61318135/81416774-d20dcc00-9167-11ea-8ef5-7dde4d9b522f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:chrome
version -79

**Additional context**

**Comment by jmgasper** [comment]
![Screen Shot 2020-05-10 at 08 46 02](https://user-images.githubusercontent.com/21790/81486793-ae976e00-929a-11ea-8c3f-cec8577da440.png)
Works fine for me
