### ISSUE TITLE
No selection options in the Terms and Groups

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/challenge-engine-ui#398]
**Describe the bug**
No option in the selection box

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com/'
2. Log in 'Ghostar / appirio123'
3. On the "Active" challenges, click the first challenge "https://challenges.topcoder-dev.com/projects/null/challenges/34c5d4d5-13fb-49c1-9b0a-548da63ad5ec/edit"
4. Click the view advanced settings
5. Click the selection box for Terms and Groups
6. Observe

**Expected behavior**
There should be options in the selection boxes in Terms and Groups

**Screenshots**
[emptyselection.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599640/emptyselection.zip)

**Desktop (please complete the following information):**
-OS: (Official Build) Built on Ubuntu , running on Ubuntu 16.04
-Browser: Chrome
-Version: 81.0.4044.122

**Additional context**
Happens in all the pages edit challenge schedule

**Comment by jmgasper** [comment]
This is just an account issue with that account in dev.  Not a bug.
