### ISSUE TITLE
Post Activating challenges from Drafts still user get message "You don't have any active projects yet!"

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#410]
Steps:-
1. Enter the URL : https://challenges.topcoder-dev.com/
2. Login as Ghostar / appirio123
3. View in the left pannel mentioned as "You don't have any active projects yet!"
4. Click on Drafts Tab - Activate any challenges

Actual Result : Post Activating challenge still user get message "You don't have any active projects yet!"

Expected Result : User should get active challenges

Browser : Chrome ,Windows 10 - OS,Version - 78

![image](https://user-images.githubusercontent.com/61318135/81417365-b22ad800-9168-11ea-8fcd-17e96bde3a7c.png)

**Comment by jmgasper** [comment]
Challenges != projects
