### ISSUE TITLE
No background of some cards

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#414]
**Describe the bug**
In some of the cards or blocks have no background all are looking same

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com and login as jcori / appirio123
2. Click on V5 challenge test
3. Click on view project in connect
4. Add the challenge name too big
5. Now observe the background all the blocks are same there is no differentiatio in background all are looking same

**Expected behavior**
There must be a background so the user can understand easily.

**Screenshots or Video**
![Snapshot 2020-05-08 20 16 30](https://user-images.githubusercontent.com/42939505/81417850-72182500-9169-11ea-8f72-2539de53d44d.png)

**Desktop (please complete the following information):**
- OS: Windows 10 (64 Bit)
 - Browser : Chrome
 - Version : 81.0.4044.138

**Comment by jmgasper** [comment]
The connect site is not in scope.
