### ISSUE TITLE
"Dropdown without any options is available.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/challenge-engine-ui#415]
"Dropdown without any options is available.

**Steps To Reproduce:**
1. Go to url ""https://challenges.topcoder-dev.com/"" 
2. Log in as Ghostar with valid credentials.
3. Click on the first challenge.
4. Change the review type to ""Internal"" and click on the displayed dropdown.

**Actual Result:**
The dropdown has no options available.

**Expected Result:**
Proper options should be displayed for the user.

OS: Windows 10
Browser: Chrome
Version 81.0.4044.138

**Screenshot:**"
[Bug 11.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599725/Bug.11.zip)

**Comment by jmgasper** [comment]
Not a bug.  It's a setup problem with the account, but the app is functioning normally.  This could have been discussed in the challenge forum.
