### ISSUE TITLE
Tag picklist value sequncing issue 

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/challenge-engine-ui#416]
**Describe the bug**
Sequence should be correct. 

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com/projects/9058/challenges/261fc4ab-44d5-4b40-9b9a-953872798076/edit
2. Scroll down to Tags picklist value
3. See error

**Expected behavior**
Tags should be in proper order alphabetically

**Screenshots or Video**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information):Macbook Air
 - OS: 10.15.2
 - Browser chrome
 - Version 81.0.4044.138

**Additional context**
![Screen Shot 2020-05-08 at 8 20 35 PM](https://user-images.githubusercontent.com/57220292/81417945-95db6b00-9169-11ea-9343-c5dc34f1fbc9.png)

**Comment by jmgasper** [comment]
There's no requirement for sorting here.
