### ISSUE TITLE
Copilot profile image highlighted when clicked

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/challenge-engine-ui#429]
**Describe the bug**
There is a blue color after clicking the copilot profile image

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com/'
2. Log in 'jcori / appirio123'
3. Click a challenge in the "Active " tab:https://challenges.topcoder-dev.com/projects/16529/challenges/c933ffa4-7cfd-4a18-971e-da19e81f0f9d/edit
4. Click the profile image
5. Observe the error

**Expected behavior**
The copilot image should not be highlighted when clicked

**Screenshots**
![color](https://user-images.githubusercontent.com/37167721/81418855-0082ab80-9156-11ea-8096-89143693a7b8.jpg)

**Desktop (please complete the following information):**
-OS: (Official Build) Built on Ubuntu , running on Ubuntu 16.04
-Browser: Chrome
-Version: 81.0.4044.122

**Additional context**
Happens in all the pages of the challenge

**Comment by jmgasper** [comment]
This is exactly what *should* be happening.  Not a bug.
