### ISSUE TITLE
Complete page is blank when clicked on reports link

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#433]
**Describe the bug**
Complete page is blank no details or no error message is shown 

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com and login as jcori / appirio123
2. Click on Another Test Project
3. Click on view project in connect
4. Now click on report observe
5. No message or no data is shown here

**Expected behavior**
There must be either error message or data should be shown

**Screenshots**
![Snapshot 2020-05-08 20 30 07](https://user-images.githubusercontent.com/42939505/81419009-2f574c80-916b-11ea-87af-59ce2dc2a5af.png)
[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599795/video.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64 Bit)
 - Browser : Chrome
 - Version : 81.0.4044.138

**Comment by jmgasper** [comment]
The connect application is not in scope.
