### ISSUE TITLE
IE 11 and FF 75  - topcoder page not loading

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#434]
Enter the URL in IE11 and FF- 75

Actual Result : Page is not loading for IE 11 & FF 75 ,loading for Chrome and Edge
Windows 10 ,

![image](https://user-images.githubusercontent.com/61318135/81419203-83fac780-916b-11ea-92cc-cdbc9aaca42c.png)

![image](https://user-images.githubusercontent.com/61318135/81419243-96750100-916b-11ea-8d1c-d0ee4620c755.png)

![image](https://user-images.githubusercontent.com/61318135/81419433-d9cf6f80-916b-11ea-852d-3ed50d1a304f.png)

**Comment by jmgasper** [comment]
Can't reproduce, and not enough information to work with.
