### ISSUE TITLE
May 7 Bug Hunt : Invalid characters are apprearing in the text box on clicking insert image icon 

### ISSUE THREAD

**Issue by payalguptagit** [topcoder-platform/challenge-engine-ui#436]
**Describe the bug**
May 7 Bug Hunt : Invalid characters are apprearing in the text box on clicking insert image icon 

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com/'
2. Login as jcori / appirio123
3. Open any Active Challenge to Edit > Scroll Down and under public specification select icon insert image, it will appear invalid character
4. Observe the label below

**Expected behavior**
On clicking insert image icon, folder should appear from where image can be selected 

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by payalguptagit** [comment]
[May 7 Bug Hunt.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599875/May.7.Bug.Hunt.zip)

**Comment by jmgasper** [comment]
That's exactly how the markdown editor work.  This is not a bug.
