### ISSUE TITLE
Asteric sign on Tags* is close than other field names

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/challenge-engine-ui#444]
**Describe the bug**
Asteric sign on Tags* is close than other field names - It should have space like Tags *

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com/projects/16529/challenges/09dc3f26-38cf-48f2-9e6b-196940fb9065/edit
2. scroll down on the Tag list
3. Observe Tags* asteric sign

**Expected behavior**
Tags* required * sign should have space *
**Screenshots or Video**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information): MAcbook air
 - 10.15.2
 - chrome
 - Version 81.0.4044.138

**Additional context**
![Screen Shot 2020-05-08 at 8 39 57 PM](https://user-images.githubusercontent.com/57220292/81419966-c8d32e00-916c-11ea-875f-b2f3ae4ca3b2.png)

**Comment by akultalwar89** [comment]
@jmgasper  - Field name Column name should be corrected? UI issue

**Comment by jmgasper** [comment]
There's no "column".  At best, this is a typo, but I don't consider this a problem at all.
