### ISSUE TITLE
Reports links appears blank

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#447]
**Describe the bug**
Report link appears blank

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com '
2. Login as jcori / appirio123
3. Click on Add another project link
4. Click on View project in connect
5. Click on Report link

**Expected behavior**
Report should not appear blank

**Screenshots**
![image](https://user-images.githubusercontent.com/61318135/81420076-01730780-916d-11ea-825e-1658acb93e51.png)

![image](https://user-images.githubusercontent.com/61318135/81420233-4eef7480-916d-11ea-9a6e-781d7a4897bd.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome, ]

**Additional context**

**Comment by jmgasper** [comment]
Connect app is not in scope.
