### ISSUE TITLE
space issue  before : when adding new Price in the edit screen

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/challenge-engine-ui#455]
**Describe the bug**
Observe after adding new price the : semi coln between prize 2: and Prize 1 : is different
**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com/projects/16531/challenges/0c7c7e12-a581-4343-a12a-f2eb4e453b82/edit
2. scroll down and click to add prize
3. Observe the : sign in 2 and 3 prize onwards. No space seen

**Expected behavior**
should have space and consistency after Prize 2: to Prize 2 : 
**Screenshots or Video**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information): Macbook Air
 - 10.15.2
 - Chrome
 - 81.0.4044.138

**Additional context**
![Screen Shot 2020-05-08 at 8 53 57 PM](https://user-images.githubusercontent.com/57220292/81421048-785cd000-916e-11ea-9f18-e98f44fa8fce.png)

**Comment by jmgasper** [comment]
Typos out of scope.
