### ISSUE TITLE
Different project name is displayed on clicking v5 challenge test

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/challenge-engine-ui#463]
Describe the bug: Different project name is displayed on clicking v5 challenge test

To Reproduce / Actual Behavior Steps to reproduce the behavior:

1.Go to 'https://challenges.topcoder-dev.com' and login using username:jcori password:appirio123
2.Click on v5 challenge test on the left nav bar 
3.Observe the title displayed at the middle of the page
4.v5 challenge test text is changing into "Something big" test

Expected behavior: Correct challenge heading should be displayed
Screenshots If applicable, add screenshots to help explain your problem.
[Something big.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599951/Something.big.zip)

Desktop (please complete the following information):

OS: [windows 7]
Browser [firefox]
Version 76.0(64-bit)
![About Firefox](https://user-images.githubusercontent.com/60426529/81421533-3ed89480-916f-11ea-9eb6-ffad959984ac.jpg)

**Comment by vikasrohit** [comment]
@acshields closing the issue as it is no more relevant with current application state. We don' have any link in the left panel as of now.
