### ISSUE TITLE
Unable to search based on specific People 

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#464]
**Describe the bug**
Unable to search based on specific People 

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com '
2. Login as 
jcori / appirio123
3. Clickon View Project connect button.
3 . Click on Dashboard link  >>Specification Tab
4. Upload a file
5. Try to add tag and specific people

**Expected behavior**
Should be able to add valid specific people.

**Screenshots**

![image](https://user-images.githubusercontent.com/61318135/81421040-7561df80-916e-11ea-8e9f-d31cc96c007d.png)
**Desktop (please complete the following information):**
 - OS: [Winodws 10]
 - Browser [ chrome]
![image](https://user-images.githubusercontent.com/61318135/81421571-47c96600-916f-11ea-92e5-ba5f7b0225ba.png)

**Additional context**

**Comment by jmgasper** [comment]
Connect app is not in scope.
