### ISSUE TITLE
While Login With Valid Credential cori_copilot / appirio123. No Details Are There.

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/challenge-engine-ui#467]
**Describe the bug**
While Login With Valid Credential cori_copilot / appirio123. No Details Are There.

**To Reproduce / Actual Behavior**

Actual Behaviour:- While Login With Valid Credential cori_copilot / appirio123. No Details Are There.

1. Go to https://challenges.topcoder-dev.com/

2. Login With Valid Credential cori_copilot / appirio123

3. Then Click On Active, New, Draft & Completed Then Observe.

4. See Screencast & Observe error

**Expected behavior**
While Login With Valid Credential cori_copilot / appirio123. There Should Be Some Details In Active, New, Draft & Completed.

**Screenshots**
[May 7 A N.mp4.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599966/May.7.A.N.mp4.zip)

**Desktop (please complete the following information):**

 - OS: macOS High Sierra Version 10.13.6 (17G12034)

 - Browser Firefox

 - Version 76.0.1 (64-bit)

**Additional context**

**Comment by jmgasper** [comment]
I see no bugs here - you're just making assumptions that are incorrect.
