### ISSUE TITLE
Display 400 error when access copilot tag

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/challenge-engine-ui#473]
**Describe the bug**
Got 400 error display when access copilot tag

**URL**
https://challenges.topcoder-dev.com/projects/16531/challenges/b1988c86-66a3-490f-9651-ab63478f3569/edit

**Step to reproduce**
1. Go to the link https://challenges.topcoder-dev.com and login with jcori/appirio123
2. Launch new  > Create challenges > Edit Challenge Schedule section
3. Tap on Copilot icon and observe the log

**Expected results**
No error trigger, it should be Display a popup warning to the user try to access copilot

**Screen shot**
![Bug8](https://user-images.githubusercontent.com/23450398/81422659-e6a29200-9170-11ea-977d-43474a666f94.jpg)
[Bug8.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4600014/Bug8.zip)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 81.0.4044.138

**Comment by vikasrohit** [comment]
Closing for now as the original flow is not possible now because auto update is disabled for all fields except the specifications.
