### ISSUE TITLE
when decreasing the windows size the texts are overlapped

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#500]
**Describe the bug**
When resizing the browser window text are overlapped page is not responsive

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com and login as jcori / appirio123
2. Now resize the width of browser
3. observe the texts are overlapped

**Expected behavior**
Page must be responsive to any window size

**Screenshots or Video**
![Snapshot 2020-05-08 20 30 07](https://user-images.githubusercontent.com/42939505/81426220-84e52680-9176-11ea-874e-29aa04bc5194.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
I'm considering this not an issue because no size requirements were given, and this is essentially a mobile / tablet size, which is out of scope.
