### ISSUE TITLE
 login Page didnot Show in IE Through https://challenges.topcoder-dev.com/

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/challenge-engine-ui#506]
## Steps to Reproduce:
- Enter  https://challenges.topcoder-dev.com/ 
![ login Page didnt show in IE](https://www.dropbox.com/s/0axzv0mixcs5myt/Login_Page_IE.png?raw=1)

## Video
https://www.dropbox.com/s/oq9pp4g6z7s5ipi/2020-05-08-19-05-30.avi?row=1

## Actual Result:
Nothing show when we enter the link

## Expected Result: 
Login page will show

## Device/OS/Browser Information:
- Device: Lenovo (laptop)
- Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
- RAM : 8 GB
- System Type: 64 Bit OS, x64-based processor
- Pen or touch: no pen or touch
-  OS: Windows 10 Home Single Language
- Browser: Internet Explorer 11 (Version: 11.778.18362.0)

**Comment by jmgasper** [comment]
IE 11 was explicitly stated as out of scope, and this can't be reproduced.
