### ISSUE TITLE
No option to upload image or insert option in Public specification editor

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#507]
**Describe the bug**
No option to upload image or insert option in Public specification editor

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com '
2. Login as jcori / appirio123
3. Edit any challenge and goto  Public specification editor
4. click on insert image icon

**Expected behavior**
Should have  upload image or insert option in Public specification editor

**Screenshots**
![image](https://user-images.githubusercontent.com/61318135/81427577-9b8c7d00-9178-11ea-8ca8-f7a7f3a6b8d0.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version []

![image](https://user-images.githubusercontent.com/61318135/81427669-bc54d280-9178-11ea-815a-0f6dcebb082f.png)

**Additional context**

**Comment by jmgasper** [comment]
Insert image works as expected, but I don't think you're understanding how the markdown editor works.
