### ISSUE TITLE
"1 day" displayed on the tooltip if user change the phase time to 12hrs

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#510]
![image](https://user-images.githubusercontent.com/42398485/81428281-ae279780-9121-11ea-8beb-9579fdb34fa2.png)

**URL:**
https://challenges.topcoder-dev.com/projects/16531/challenges/3f6452f7-db6a-4055-86fb-ffc681ac69be/edit

**Reproduction Steps:**

1. Open the application and Login as a valid user (jcori)
2. Go to 'Draft' tab and click on a challenge
3. Go to 'Challenge Schedule :' > Edit
4. Change the Appeals Response=12hrs
5. Now Click on Edit again
6. Hover over the Appeals Response

**Actual Result:** 

- "1 day" displayed on the tooltip if user change the phase time to 12hrs

**Expected Result:** 

- Should display as 12 hrs

**Device/OS:** 

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 10 64bit (1909, 18363.815)

**Browser Information:** 

- **Browser(s):** Google Chrome 81.0.4044.138

**Comment by jmgasper** [comment]
Functionality isn't broken here - changing this to a UI issue.

**Comment by jmgasper** [comment]
This is an issue with the library.  Not going to fix it.
