### ISSUE TITLE
On click of quote in editor text is not starting with quotes ""

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#511]
**Describe the bug**
editor text is not starting with quotes ,starting with > ""

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com '
2. Login as jcori / appirio123
3. Click on any challenges 
4. Goto public specification editor
5 Enter a text and click on Quotes ""

**Expected behavior**
Text should start with quotes  

**Screenshots**
![image](https://user-images.githubusercontent.com/61318135/81428007-443adc80-9179-11ea-99dc-6759f3467e17.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [81]

**Additional context**

**Comment by jmgasper** [comment]
Again, this is just not understanding markdown or the markdown editor.
