### ISSUE TITLE
Show password icon is not changing when clicked on it, it remains same

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#523]
**Describe the bug**
Show password icon is not changing when clicked on it, it remains sameug is. on login page

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com 
2. Fill the user name and password
3. now click on show password icon
4. observe the icon is not changing, user will not be able to know it is showing password or not, when password is not entered

**Expected behavior**
Show password icon must toggle so user will able to know when the password is visible and when not.

**Screenshots**
[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4600623/video.zip)

**Desktop (please complete the following information):**
  - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
Login page is out of scope.  This could have been asked about and clarified in the forum.
