### ISSUE TITLE
 Can't Enter UserName and Password Due to Overlapping Inputs

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/challenge-engine-ui#528]
## Steps to Reproduce:
- Open Internet Explorer, enter link "https://accounts.topcoder-dev.com/#!/member?retUrl=https:%2F%2Fchallenges.topcoder-dev.com%2F"

## Actual Result:
Cant enter user name due to overlapping input

![login_ui_overlapping](https://www.dropbox.com/s/rxhwsgmu304ybqy/input_overlapping.png?raw=1)

## Expected Result:
Can enter user name

## Device/OS/Browser Information:
- Device: Lenovo (laptop)
- Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
- RAM : 8 GB
- System Type: 64 Bit OS, x64-based processor
- Pen or touch: no pen or touch
-  OS: Windows 10 Home Single Language
- Browser: Internet Explorer 11 (Version: 11.778.18362.0)

**Comment by jmgasper** [comment]
accounts.topcoder-dev.com is out of scope.
