### ISSUE TITLE
'Edit Challenge' page title is incorrect

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#535]
![image](https://user-images.githubusercontent.com/42398485/81436725-935c1f80-912f-11ea-8a98-b98aa1e6c754.png)

**URL:**
https://challenges.topcoder-dev.com/projects/16539/challenges

**Reproduction Steps:**

1. Open the application and Login as a valid user (jcori)
2. Select a Project > Click Launch New > Fill all > Click Create Challenge
3. Check the Title

**Actual Result:** 

- 'Edit Challenge' page title is incorrect because this is not the editing process this create challenge process

**Expected Result:** 

- Should display as 'Create Challenge' 

**Device/OS:** 

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 10 64bit (1909, 18363.815)

**Browser Information:** 

- **Browser(s):** Google Chrome 81.0.4044.138

**Comment by jmgasper** [comment]
Actually, at this point, the challenge is created.  The first page creates the challenge in the system, when the name, type, and track are selected, so `Edit Challenge` is technically correct here.
