### ISSUE TITLE
Edit "Challenge Schedule" must indicate that the values are in hours 

### ISSUE THREAD

**Issue by ranjyotiprakash** [topcoder-platform/challenge-engine-ui#536]
**Describe the bug**
Edit "Challenge Schedule" must indicate that the values are in hours for the available text-boxes : 
- Registration
- Review
- Appeals Response
- Appeals
- Submission

**To Reproduce / Actual Behavior**

1. login to https://challenges.topcoder-dev.com with credentials "jcori / appirio123"
2. Click on "Another Test project"
3. Click on "Launch New"
4. Select a "Track" , a "Type" and give a name to the challenge on "Create New Challenge" page
5. Click on "Create Challenge"
6. Scroll to "Challenge Schedule" and click on "Edit"
7. Check the 5 options listed now, there is no indication on the UI that these values are supposed to be in hours.

**Expected behavior**
There should be a label either in the left hand side caption or beside the textbox saying "hrs/hours".

**Screenshots or Video**
<img width="1404" alt="Screenshot 2020-05-08 at 11 56 15 PM" src="https://user-images.githubusercontent.com/5712602/81437135-4eb0a280-9188-11ea-9405-77f2eb681bad.png">

**Desktop (please complete the following information):**

- OS: macOS Mojave Version 10.14.6
- Browser : Chrome
- Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

**Comment by jmgasper** [comment]
The placholder text indicates the values are in hours.
