### ISSUE TITLE
'Manager' is listed as Copilot

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#539]
![image](https://user-images.githubusercontent.com/42398485/81437611-12058c80-9131-11ea-8cf7-81f17ee263e3.png)

![image](https://user-images.githubusercontent.com/42398485/81437628-1af65e00-9131-11ea-8291-019b0d4931c3.png)

**URL:**
https://challenges.topcoder-dev.com/projects/16539/challenges/92e5b657-e754-4bdc-928c-4ef00badd52a/edit

**Reproduction Steps:**

1. Open the application and Login as a valid user (jcori)
2. Select a Project (eg: Test & QA) > Click Launch New > Fill all > Click Create Challenge
3. Finish creating the project and open the challenge
4. Check the Copilot field

**Actual Result:** 

- 'Manager' is listed as Copilot

**Expected Result:** 

- Should not display the manager as Copilot in the Copilot field

**Device/OS:** 

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 10 64bit (1909, 18363.815)

**Browser Information:** 

- **Browser(s):** Google Chrome 81.0.4044.138

**Comment by codejamtc** [comment]
If this is allowed the field name should be `Manager(s)/Copilot(s)`

**Comment by acshields** [comment]
@vikasrohit - only Copilots should be displayed. Do you agree?

**Comment by vikasrohit** [comment]
I think we might need to allow managers in the list because there are challenges where managers are acting as copilot for certain challenges e.g. I acted as copilot for some of my challenges.

**Comment by vikasrohit** [comment]
> I think we might need to allow managers in the list because there are challenges where managers are acting as copilot for certain challenges e.g. I acted as copilot for some of my challenges.
@acshields can we close this?

**Comment by acshields** [comment]
@vikasrohit - Yes, we can close this.
