### ISSUE TITLE
Multiple challenges with same name are getting created successfully

### ISSUE THREAD

**Issue by ranjyotiprakash** [topcoder-platform/challenge-engine-ui#548]
**Describe the bug**
Multiple challenges with same name are getting created successfully. This should not be allowed because this may create a confusion with the users of the system. 

**To Reproduce / Actual Behavior**

1. login to https://challenges.topcoder-dev.com with credentials "jcori / appirio123"
2. Click on "Another Test project"
3. Click on "Launch New"
4. Select a "Track" , a "Type" and give a name (for e.g "testing") to the challenge on "Create New Challenge" page
5. Click on "Create Challenge"
6. Fill in all the details on "Edit Challenge" page and "Launch As Active".
7. Repeat Step 2 to Step 6 and use the same name (for e.g. "testing") for the new challenge also and launch it as Active.
8. Both the challenges are active and can be seen on the "Active" challenges. 

**Expected behavior**
Web Application should not allow challenges with the same name to be created.

**Screenshots**
<img width="1137" alt="Screenshot 2020-05-09 at 12 45 02 AM" src="https://user-images.githubusercontent.com/5712602/81441425-5de71e80-918f-11ea-838b-d1f08d2bfe89.png">
<img width="1124" alt="Screenshot 2020-05-09 at 12 46 44 AM" src="https://user-images.githubusercontent.com/5712602/81441441-68091d00-918f-11ea-8c77-c2a93f4b8de8.png">

**Desktop (please complete the following information):**

- OS: macOS Mojave Version 10.14.6
- Browser : Chrome
- Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

**Comment by jmgasper** [comment]
There's no requirement for a challenge name to be unique.
