### ISSUE TITLE
While Try To Underline, Italic Or Bold Its Not Changing Font

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/challenge-engine-ui#559]
**Describe the bug**
While Try To Italic Or Bold Its Not Changing Font

**To Reproduce / Actual Behavior**
Actual Behaviour:- While Try To Underline, Italic Or Bold Its Not Changing Font

1. Go to https://challenges.topcoder-dev.com/

2. Login As Valid Credential jcori / appirio123

3. Click on The TaaS project > Click View Project In Connect > Click Messages > Fill details 

4. Try To Font As Underline, Bold Or Italic In First Field.

5. See Screencast & Screenshot Then Observe.

**Expected behavior**
While Try To Underline, Italic Or Bold It Should Change Font

**Screenshots**
[May 7 A I.mp4.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4601593/May.7.A.I.mp4.zip)
[May 7 A I.png.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4601594/May.7.A.I.png.zip)

**Desktop (please complete the following information):**
 
- OS: macOS High Sierra Version 10.13.6 (17G12034)

- Browser Chrome
 
- Version 81.0.4044.138 (Official Build) (64-bit)

**Console Log**
[May 7 A I.log.txt.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4601597/May.7.A.I.log.txt.zip)

**Comment by jmgasper** [comment]
The connect app is not in scope.
