### ISSUE TITLE
Radio Button Should Not Show Options

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/challenge-engine-ui#562]
**Describe the bug**
Radio Button Should Not Show Options

**To Reproduce / Actual Behavior**
Actual Result:- Radio Button Is Showing Options

1. Go to https://challenges.topcoder-dev.com/

2. Login With Valid Credential jcori / appirio123

3. Click on Test TaaS Project > Select View Project In Connect

4. Click On Radio Button Near Project Is Active

5. See Screencast & Screenshot Then Observe error

**Expected behavior**
Radio Button Should Not Show Options

**Screenshots**
[May 7 A R.mp4.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4601951/May.7.A.R.mp4.zip)
[May 7 A R.png.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4601952/May.7.A.R.png.zip)

**Desktop (please complete the following information):**
 
- OS: macOS High Sierra Version 10.13.6 (17G12034)

 - Browser Chrome
 
- Version 81.0.4044.138 (Official Build) (64-bit)

**Console Log**
[May 7 A R.log.txt.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4601965/May.7.A.R.log.txt.zip)

**Comment by jmgasper** [comment]
The connect app is not in scope.
