### ISSUE TITLE
No option to select multiple copilot for a challenge

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#574]
Every challenge should have an option to select multiple copilots 
Copilot icon should be clickable to redirect to copilot details

![image](https://user-images.githubusercontent.com/61318135/81462182-4a0edd00-91ce-11ea-9b37-df892953394d.png)

**Comment by jmgasper** [comment]
@rootelement - Do we want to support multiple copilots for a challenge?  I know we've talked about that in the past, but wasn't sure if that was something that Topcoder 100% wanted.

**Comment by ab668685** [comment]
Suggestion:Suppose unfortunately a copilot is on leave or unable to proceed ,in that situation it can be assigned to other copilot aswell.

**Comment by rootelement** [comment]
For now, leave it as single copilot. We can change it, but not assign more than one to a challenge.
