### ISSUE TITLE
Project details,Tell us about your project,Do you have referral labels are not displayed completely

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#575]
**Describe the bug**
Project details are not displayed completely

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com '
2. Login as jcori / appirio123
3. Click on Test Taas project link >>View project in connect
4. Click on Scope link
4 View the Tell us about your project,Do you have referral

**Expected behavior**
Project details label should display properly

**Screenshots or Video**

![image](https://user-images.githubusercontent.com/61318135/81462537-bd195300-91d0-11ea-9d34-837bf7e92386.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [81]

**Additional context**

**Comment by jmgasper** [comment]
The connect app is not in scope.
