### ISSUE TITLE
Invited people timestamp not displayed in correct date format

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#576]
**Describe the bug**
Invited people timestamp not displayed in correct date format

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com '
2. Enter the login jcori / appirio123
3. Click on Test TaaS Project link
4. Click on View project in connect
5. Click on Manage topcoder link
6. Add a copilot and view the timestamp

**Expected behavior**
Invited people should display in proper timestamp 

**Screenshots or Video**

![image](https://user-images.githubusercontent.com/61318135/81462675-e71f4500-91d1-11ea-8f6b-74243141efc9.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [ chrome]
 - Version [81]

**Additional context**

**Comment by jmgasper** [comment]
The connect app is not in scope.
