### ISSUE TITLE
Can't spell check - mentioned as can\'t 

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#577]
**Describe the bug**
Can't spell check

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com .'
2. Login as jcori / appirio123
3. Click on Taas Project link
4. Click on View project connect button.
5. Click on Manage Topcoder -Try to invite same copilot again
6. User get message "Project Member(s) can\'t be invited again. Please remove them from list."

**Expected behavior**
Can\t should be written as Can't

**Screenshots or Video**

![image](https://user-images.githubusercontent.com/61318135/81462866-1aae9f00-91d3-11ea-99ca-c1e3a6529282.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [e.g. chrome]
 - Version [81]

**Additional context**

**Comment by jmgasper** [comment]
The connect app is not in scope.
