### ISSUE TITLE
Only Save changes button is displayed no options are there (Save changes button has no meaning)

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#578]
**Describe the bug**
Only Save changes button is displayed no options are there (Save changes button has no meaning)

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com and login as jcori / appirio123
2. Click on Test & QA project
3. Now click on view project in connect
4.Now click on scope and scroll down
5. Observe the last block has only save changes button is there, no option there

**Expected behavior**
There must be either some fields should available or no save changes button should there

**Screenshots or Video**
![Snapshot 2020-05-08 20 30 07](https://user-images.githubusercontent.com/42939505/81463236-96115000-91d5-11ea-8c69-cf15fc744fc7.png)

[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4602582/video.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
The connect app is not in scope.
