### ISSUE TITLE
On clicking on Specification link in Bug discovery project no function is performed, it is taking  on blank page

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#579]
**Describe the bug**
On clicking on Specification link in Bug discovery project no function is performed, it is taking  on blank page

**To Reproduce / Actual Behavior**
1. Go to https://connect.topcoder-dev.com/projects/7761 (You must be logged in with jcori / appirio123)
2. Click on Specification
3. Now observe the behavior a blank page opens

**Expected behavior**
There must be any details of the page should available

**Screenshots**
[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4602588/video.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
The connect app is not in scope.
