### ISSUE TITLE
Invite More people >> Invalid saved messages

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/challenge-engine-ui#580]
**Describe the bug**

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com '
2. Login as jcori / appirio123
3. Click on Taas Project link >> View connect project button .
4. Click on Manage link of Topcoder
5 Try to add invite @Ghostar with Manager / Copilot role- Get message user invited successfully 
6. Ghostar cannot be invited with a manager role

**Expected behavior**
Correct validation message should display

**Screenshots or Video**
If applicable, add screenshots or video to help explain your problem.
![image](https://user-images.githubusercontent.com/61318135/81463519-c22dd080-91d7-11ea-8d52-64cd6592cfc7.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [81]

**Additional context**

**Comment by jmgasper** [comment]
The connect app is not in scope.
