### ISSUE TITLE
Alignment of date field icons are not proper in assests library page

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#581]
**Describe the bug**
Alignment of date field icons are not proper in assests library page

**To Reproduce / Actual Behavior**

1. Go to https://connect.topcoder-dev.com/projects/16531 (You must be logged in with jcori / appirio123)
2. Click on Assets Library
3. Now Click on Date now add any date
4. Observe the icons are not properly aligned

**Expected behavior**
The icon must be properly aligned 

**Screenshots or Video**
![Snapshot 2020-05-08 20 30 07](https://user-images.githubusercontent.com/42939505/81463671-d920f280-91d8-11ea-8b4d-b3ad685fee12.png)
[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4602619/video.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
The connect app is not in scope.
