### ISSUE TITLE
Labels and text are not properly aligned

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#582]
**Describe the bug**
Labels and text or their values is not properly aligned

**To Reproduce / Actual Behavior**

1. Go to https://connect.topcoder-dev.com/projects/16531 (You must be logged in with jcori / appirio123)
2. Click on Edit icon of any phase
3. Now observe the Duration(Days) and progress(%) values are not properly aligned to it

**Expected behavior**
Values must be properly aligned to labels

**Screenshots or Video**
![Snapshot 2020-05-08 20 30 07](https://user-images.githubusercontent.com/42939505/81463815-25b8fd80-91da-11ea-9a79-e65e8ad73d75.png)
[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4602641/video.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
The connect app is not in scope.
