### ISSUE TITLE
Customer filter dialog is overlapping on the other text (ie Topcoder)

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#584]
**Describe the bug**
Customer filter dialog is opened it is overlapping on the other text (ie Topcoder) and also the text is showing over dialog

**To Reproduce / Actual Behavior**
1. Go to https://connect.topcoder-dev.com/projects and login as jcori / appirio123
2. Click on Customer tab
3. Now observe the popup dialog is appeared which is overlapped the text topcoder and also topcoder is showing on it

**Expected behavior**
There must not be overlapping or the topcoder text should not show

**Screenshots or Video**
![Snapshot 2020-05-08 20 30 07](https://user-images.githubusercontent.com/42939505/81464000-cd82fb00-91db-11ea-99ac-250ee52fc212.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
The connect app is not in scope.
