### ISSUE TITLE
After Searching a project by name, it is showing as "No results found based on current search criteria." for a small bit of time then search result is coming

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#586]
**Describe the bug**
After Searching a project by name, it is showing as "No results found based on current search criteria." for a small bit of time then search result is coming (When the project is available)

**To Reproduce / Actual Behavior**

1. Go to https://connect.topcoder-dev.com/projects (You must belogin as jcori / appirio123
2. Now type any project which is available in search bar and hit enter
3. Observe the  "No results found based on current search criteria." is showing for a small bit of time then result is appearing

**Expected behavior**
Either it should show a loading message or it shouldn't show no result found

**Screenshots**
[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4602674/video.zip)

**Desktop (please complete the following information):**
- OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
The connect app is not in scope.
