### ISSUE TITLE
Same Challenge Shown Different Assignee Copilots

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/challenge-engine-ui#588]
## Steps to Reproduce:
- Login as JCori
- Go to **Active Challenges** Tab
- Choose and Click **Thomas Test 3** Challenge 
--In different Browser or Window:
- Login as Ghostar
- Go to **Active Challenges** Tab
- Choose and Click **Thomas Test 3** Challenge 
- Compare assignee copilot

## Actual Result:
 When we login as JCori, assignee copilot are Pshah Manager and Tony J, but when we login as Ghostar asignee copilot are JCori and Ghostar.

- When we login as jcori. Result:
![login as jcori](https://www.dropbox.com/s/am4e24m6js79m24/copilot_jcori.png?raw=1)

- When we login as ghostar. Result:
![login as ghostar](https://www.dropbox.com/s/uxoi4meaweobdgu/copilot_ghostar.png?raw=1)

## Expected Result:
Both users should showing the same assignee copilots.

## Device/OS/Browser Information:
- Device: Lenovo (laptop)
- Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
- RAM : 8 GB
- System Type: 64 Bit OS, x64-based processor
- Pen or touch: no pen or touch
-  OS: Windows 10 Home Single Language
- Browser: Google Chrome (81.0.4044.138 (Official Build) (64-bit)) and Firefox(76.0.1 (64-bit))

**Comment by jmgasper** [comment]
You're looking at two separate challenges in two separate projects, just with the same name, as far as I can tell from the screenshots.
