### ISSUE TITLE
Edit Challenge > Copilot link is not navigating to profile/ any page.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/challenge-engine-ui#590]
**Describe the bug**
Copilot name on selection to be redirected to respective page.

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com/projects/7761/challenges/e8a25c1c-6cbe-40e9-bf1b-7c41c6f43abb/edit
2. Click on name near Copilot 
3.  It get selected but is not redirecting to any page.

**Expected behavior**
Copilot name is expected to redirected to profile / dashboard page.

**Screenshots**
[Bug7_new.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4602892/Bug7_new.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81

**Additional context**

**Comment by jmgasper** [comment]
This is fundamentally wrong and not at all what we want.  Please don't make assumptions about what the functionality should be.  If something isn't clear, you are free to ask in the forums.
