### ISSUE TITLE
Edit Challenge > Shift + Tab is not working near Public Specification

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/challenge-engine-ui#594]
**Describe the bug**
Keyboard navigation keys not working near Public specification.

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com/projects/7761/challenges/588c5dbb-1322-4285-b620-9c187a204253/edit
2. Click on Start date field
3. Tab will move the cursor to PUblic Specification.
4. Shift + tab is not working in public specfiication textbox by keeping the cursort at the start of the first line.

**Expected behavior**
Shift + tab should work in public specification combo box

**Screenshots or Video**
[Bug10_new.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4602958/Bug10_new.zip)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 81

**Additional context**

**Comment by jmgasper** [comment]
This is how the markdown editor functions and is expected.
