### ISSUE TITLE
Show password icon is overlapped when password is too long on login page

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#600]
**Describe the bug**
Show password icon is overlapped when the password is too long on the login page, the user is not able to see icon properly

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com 
2. Enter the username
3. Enter the password very long till end of the text field
4. Now observe the show password icon is overlapping the password and not visible properly

**Expected behavior**
Show Password icon should not overlap to text

**Screenshots or Video**
![Snapshot 2020-05-08 20 30 07](https://user-images.githubusercontent.com/42939505/81468402-fd8ec600-91fc-11ea-9cf8-34b884beb72d.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Firefox
 - Version 76.0

**Comment by jmgasper** [comment]
Note that this is accounts.topcoder-dev.com.  Out of scope.
