### ISSUE TITLE
Logout is not terminating the session open in another tab in the same browser

### ISSUE THREAD

**Issue by ranjyotiprakash** [topcoder-platform/challenge-engine-ui#601]
**Describe the bug**
After opening multiple tabs in a session, and then logging out from one of the tabs doesn't close the session for the User. I was able to access the challenges and everything else in another tab.

**To Reproduce / Actual Behavior**
1. login to https://challenges.topcoder-dev.com with credentials "jcori / appirio123"
2. After login, right click on the available challenges to "Open it in new tab".
3. Then access the challenge in new tab, do some updates.
4. Stay in this new tab and Click "Logout Icon" available in top right corner and User will be logged out successfully.
5. Now, Navigate to the first tab and "Search for a challenge" or "Create New Challenge" or other actions possible on the web app.

**Expected behavior**
Logging out from one tab should close the session for the User and performing an action on an already existing duplicate tab should fail and the User should be redirected to login Page or Should be shown a "Permission Denied" error. 

**Screenshots**
<img width="1440" alt="Screenshot 2020-05-09 at 1 46 48 PM" src="https://user-images.githubusercontent.com/5712602/81468307-3f6b3c80-91fc-11ea-81ec-f36a3d2476da.png">
This Screenshot were taken after logging out from another tab.

<img width="1435" alt="Screenshot 2020-05-09 at 1 46 37 PM" src="https://user-images.githubusercontent.com/5712602/81468306-3b3f1f00-91fc-11ea-8f0c-a5343b9ce752.png">

Video Proof : 
[logout_vulnerability.mov.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4602999/logout_vulnerability.mov.zip)

**Desktop (please complete the following information):**

- OS: macOS Mojave Version 10.14.6
- Browser : Chrome
- Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
Session management is an important part of a web application. 

https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html

https://kennel209.gitbooks.io/owasp-testing-guide-v4/en/web_application_security_testing/testing_for_logout_functionality_otg-sess-006.html

**Comment by jmgasper** [comment]
@rootelement - I've noticed with other tools as well, like TC-X.  Is there a specific way we should be logging out?

**Comment by rootelement** [comment]
This is a problem with accounts app in dev, not our app. We'll have to test this when it goes to prod.

I know they're working on accounts app in dev, so I assume this is something to do with that.
