### ISSUE TITLE
Drop down icon is overlapped (hidden) by text in text field when entered text is too long on registration page in firefox while working fine in other browser

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#602]
**Describe the bug**
Drop down icon is overlapped (hidden) by text in text field when entered text is too long on registration page

**To Reproduce / Actual Behavior**
1. Go to https://accounts.topcoder-dev.com/member/registration
2. Enter the too long text in country field
3. Observe the drow down icon is overlapped by the text

**Expected behavior**
Dropdown icon should not overlap by text

**Screenshots or Video**
![Snapshot 2020-05-08 20 30 07](https://user-images.githubusercontent.com/42939505/81469127-f36ec680-9200-11ea-84e3-318e60b6069d.png)

**Desktop (please complete the following information):**
  - OS:  Windows 10 (64 Bit)
 - Browser Firefox
 - Version 76

**Comment by jmgasper** [comment]
Note that this is accounts.topcoder-dev.com.  Out of scope.
