### ISSUE TITLE
Integrate challenge editor page with the API

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-engine-ui#61]
Swagger: https://github.com/topcoder-platform/challenge-api/tree/develop/docs

### 1. Run the API locally

Follow the instructions from https://github.com/topcoder-platform/challenge-api to set up and run the API locally.

---

### 2. Challenge types

Call the `/challengeTypes`  to fetch the available challenge types that will populate the following section:

<img width="864" alt="Screenshot 2019-06-08 at 13 09 49" src="https://user-images.githubusercontent.com/4612921/59145591-c3b2af80-89ee-11e9-9f80-4c7be4312a79.png">

---

### 3. Groups

Call the `api.topcoder-dev.com/v3/groups` endpoint to fetch the available groups that will be used to render the following section:
<img width="900" alt="Screenshot 2019-06-08 at 13 26 53" src="https://user-images.githubusercontent.com/4612921/59145766-18572a00-89f1-11e9-9a9a-e2cde98bae68.png">

---

### 4. Timeline

1. Call the `/challengePhases` endpoint to fetch the available phases.
2. Call the `/timelineTemplates` endpoint to fetch the available timeline templates.
3. Dates should be based on the user's local timezone. Use a 3rd party lib to identify the user's local timezone and show it on the right corner.
4. Phase dates should also be shown when the section is collapsed similar to how it's currently showing up when you click `Edit` from the listings page.

**Important**: Dates should be passed to the API as UTC and not based on the user's local timezone.

Use the response from *2* to populate the dropdown from the screenshot below.
Based on the selected timeline template, populate the phases list with the data from the response of *1*.

<img width="920" alt="Screenshot 2019-06-08 at 13 31 09" src="https://user-images.githubusercontent.com/4612921/59145836-180b5e80-89f2-11e9-984c-647870dbc2dd.png">

---

### 5. Markdown editor

Use the following 3rd part tool as the Markdown editor:
https://github.com/sparksuite/simplemde-markdown-editor

---

### 6. Submit a challenge

Clicking `Save as Draft` will set the `status` to `Draft` while `Launch` will set it to `Active`.

Clicking `Save as Draft` will save the challenge immediately while `Launch` will show the confirmation popup first.

To save/launch the challenge, `POST` the challenge to the `/challenges` endpoint.

After saving/launching the challenge, take the user to the challenge edit page.

---

### 7. Attachments

- Use the `/challenges/:challengeId/attachments` endpoint to upload an attachment.
- Use the `/challenges/:challengeId/attachments/:attachmentId` endpoint to download an attachment.
- To delete an attachment, you need to remove it from the challenge object. Then, once we save the updated challenge object (see below), the backend will delete it.

---

### 8. Edit a challenge

- To fetch an existing challenge, use the `GET` `/challenges/:challengeId` endpoint.
- To update/edit a challenge, make a `PUT` request to the `/challenges/:challengeId` endpoint.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas will this be open?

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji no, not yet. I may open a few issues today. Stay tuned!
