### ISSUE TITLE
In Edge, when typing password in login page an overlapped icon is coming over the show password icon and also the cross icon is coming when clicked on show password icon

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#612]
**Describe the bug**
In Edge, when typing password in login page an overlapped icon is coming over the show password icon and also the cross icon is coming when clicked on show password icon

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com 
2. Click on password field and start typing password
3. Now observe there is another icon overlapped over show password icon
4. Now click on show password icon and observe a cross icon is over the show password icon

**Expected behavior**
There must not be any overlapping of icons, only one icon should display.

**Screenshots**
[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4603272/video.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Edge 
 - Version 44.18362.449.0

**Comment by jmgasper** [comment]
Note that this is accounts.topcoder-dev.com.  Out of scope.
