### ISSUE TITLE
May 7 Bug Hunt : No shortcuts is displaying on bold, italic, underline, etc. showing Add your post in Massage option

### ISSUE THREAD

**Issue by payalguptagit** [topcoder-platform/challenge-engine-ui#613]
**Describe the bug**
May 7 Bug Hunt : No shortcuts is displaying on bold, italic, underline, etc. showing Add your post in Massage option

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder-dev.com/

2. Login As Valid Credential jcori / appirio123

3. Click on Another Test Project > Click View Project In Connect > Click Messages > put cursor on bold, italic, underline, etc. 

4. No shortcut is display on same but shortcuts are working.

5. See Screenshot & video Then Observe.
**Expected behavior**
Shortcuts should appear if we put cursor on Bold, italic, underline, etc. tab.
**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by payalguptagit** [comment]
[May 7 Bug Hunt.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4603298/May.7.Bug.Hunt.zip)

**Comment by jmgasper** [comment]
Connect app is not in scope.
