### ISSUE TITLE
In Edge, Registration page, username, email text field have too much padding from right side

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#614]
**Describe the bug**
In Edge, Registration page's username and email text field has too much padding from the right side and also the cross icon is coming in between the text field

**To Reproduce / Actual Behavior**
1. Go to https://accounts.topcoder-dev.com/member/registration
2. Now type text in the username field and observe the cross icon is coming in center
3. Now same as in email field
4. Now type text in password field and observe another show password icon is coming
5. Now type text in country field and observe cross icon is overlapping over the drop down icon

**Expected behavior**
There must be less padding from right side so user will get more space to type

**Screenshots**
[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4603294/video.zip)

![Snapshot 2020-05-08 20 30 07](https://user-images.githubusercontent.com/42939505/81471645-28cee080-9210-11ea-947c-79b868a59fc2.png)
![Snapshot 2020-05-09 15 58 52](https://user-images.githubusercontent.com/42939505/81471648-2b313a80-9210-11ea-9735-bb661ee8bf6d.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Edge
 - Version 44.18362.449.0

**Comment by jmgasper** [comment]
Note that this is accounts.topcoder-dev.com.  Out of scope.
