### ISSUE TITLE
Email validation on registration page get fails when along with @ and Dot(.) special characters are included. It shows only red block not any error message.

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#622]
**Describe the bug**
Email validation on registration page get fails when along with @ and Dot(.) special characters are included. It shows only red block not any error message.
exp - raj@g.#com

**To Reproduce / Actual Behavior**
1. Go to https://accounts.topcoder-dev.com/member/registration
2. Click email field and insert the value as raj@g.#com
3. Now observe there is only red block is showing not any error message

**Expected behavior**
Email must be validated to all the characters and all the cases and error must be shown properly

**Screenshots**
[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4603486/video.zip)

**Desktop (please complete the following information):**
  - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
Note that this is accounts.topcoder-dev.com.  Out of scope.
