### ISSUE TITLE
On Registration page Username validation is not working properly, as it mentioned 2 to 15 characters but also accepting 1 character with other symbols

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/challenge-engine-ui#624]
**Describe the bug**
On Registration page Username validation is not working properly, as it mentioned 2 to 15 characters but also accepting 1 character with other symbols.
if it is treating symbols as a character so it should not show an error when no English alphabets are entered but if it is not then it should not accept only 1 English alphabet

**To Reproduce / Actual Behavior**
1. Go to https://accounts.topcoder-dev.com/member/registration
2. Click on username field
3. Now paste the following value -{}_..[]j as there is only 1 alphabetical character but it will accept this.
4. observe it is mentioned that 2 to 15 characters with symbols but it is also taking one character

**Expected behavior**
It should properly validate that two alphabets are entered along with symbols(if there)

**Screenshots**

[video.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4603514/video.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64 Bit)
 - Browser Chrome
 - Version 81.0.4044.138

**Comment by jmgasper** [comment]
Note that this is accounts.topcoder-dev.com.  Out of scope.
