### ISSUE TITLE
Challenge details API can be requested and sensitive data can be fetched without authentication

### ISSUE THREAD

**Issue by ranjyotiprakash** [topcoder-platform/challenge-engine-ui#628]
**Describe the bug**
Challenge details API can be requested and sensitive data can be fetched without authentication. This is a serious information disclosure vulnerability due to which anyone can access the "Challenge Details" without being authenticated.

**To Reproduce / Actual Behavior**

1. login to https://challenges.topcoder-dev.com with credentials "jcori / appirio123"
2. Enable Inspector from Browser's developer tools and go to network tab in browser inspector
3. Click on one of the Active challenges
4. Notice the URLs being fetched in network tab of inspector, Copy link URLs for each GET request to "https://api.topcoder-dev.com"
5. Open a browser window in incognito mode and paste the URL copied and click enter
6. You can see the JSON data for the challenge in the Browser
7. This can be validated by opening a terminal and doing wget on the copied URL will give the JSON data for the challenge.
8. There are many API endpoints which return data without authentication.

**Expected behavior**
API endpoints must never give sensitive data without authentication and must fail with a "401 permission denied/403 Forbidden" or other valid HTTP status code with proper error message "You are not authorised to perform this action"

**Screenshots**
<img width="1430" alt="Screenshot 2020-05-09 at 8 20 36 PM" src="https://user-images.githubusercontent.com/5712602/81477055-2467ef00-9233-11ea-8004-ff4836054d5f.png">
<img width="1433" alt="Screenshot 2020-05-09 at 8 20 47 PM" src="https://user-images.githubusercontent.com/5712602/81477060-292ca300-9233-11ea-9e48-c9bc9a9e1f5d.png">

<img width="1343" alt="Screenshot 2020-05-09 at 8 29 22 PM" src="https://user-images.githubusercontent.com/5712602/81477168-ef0fd100-9233-11ea-9240-9921707cea7e.png">
<img width="1340" alt="Screenshot 2020-05-09 at 8 29 37 PM" src="https://user-images.githubusercontent.com/5712602/81477172-f59e4880-9233-11ea-8247-90f55ead3276.png">
<img width="1346" alt="Screenshot 2020-05-09 at 8 29 48 PM" src="https://user-images.githubusercontent.com/5712602/81477177-fcc55680-9233-11ea-8367-b5562fe552d8.png">
<img width="1339" alt="Screenshot 2020-05-09 at 8 30 09 PM" src="https://user-images.githubusercontent.com/5712602/81477184-03ec6480-9234-11ea-85df-ec72dcb4a3af.png">

[unauthenticate_480.mov.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4603812/unauthenticate_480.mov.zip)
[unauthenticated_api_requests_wget.txt.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4603814/unauthenticated_api_requests_wget.txt.zip)

**Desktop (please complete the following information):**

- OS: macOS Mojave Version 10.14.6
- Browser : Chrome
- Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
API endpoints which are accessible without authentication

https://api.topcoder-dev.com/v5/challenges/08e78f10-89bb-4cd0-a48a-b3625c895f34
https://api.topcoder-dev.com/v5/challenge-phases
https://api.topcoder-dev.com/v5/timeline-templates
https://api.topcoder-dev.com/v5/challenge-types?isActive=true
https://api.topcoder-dev.com/v4/technologies

**Comment by jmgasper** [comment]
This is expected - we use this information on the challenges listing, which doesn't require login.
