### ISSUE TITLE
WIP Filter Timeline Templates based on Selected Type

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-engine-ui#665]
use this API call to populate the Timeline Templates dropdown:
`/v5/challenge-timelines?typeId=<uuid>`

**Comment by drasticdpk** [comment]
Verified on Dev env.
Reference :
![image](https://user-images.githubusercontent.com/25297859/84343756-c67b4e00-abc8-11ea-881c-a8c55106eb4c.png)
![image](https://user-images.githubusercontent.com/25297859/84343983-4ef9ee80-abc9-11ea-8e9a-fed17e52f91f.png)

**Comment by vikasrohit** [comment]
It was verified on dev by QA and moved to production as well. Closing.
As reference, it can not be verified as of now because timeline templates field is hidden from UI for now because v4 challenge api does not support timeline edits.
