### ISSUE TITLE
Standard Design "Edit" Event Sequence Out of Order

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/challenge-engine-ui#666]
**Describe the bug**
When "Edit" is clicked for the Standard Design template, the phase events appear out of order.

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com/projects/6640/challenges/32c3fd5f-3a3b-470e-a463-647899504b24/edit'
2. Select 'Standard Design' timeline template
3. Click on 'Edit'

**Expected behavior**
I believe the phases should be listed as follows:
1. Specification Submission
2. Specification Review
3. Registration
4. Submission
5. Checkpoint Submission
6. Checkpoint Screening
7. Checkpoint Review
8. Screening
9. Final Fixes
10. Final Review
11. Approval

**Screenshots or Video**
<img width="711" alt="Screen Shot 2020-05-28 at 2 24 25 PM" src="https://user-images.githubusercontent.com/41118149/83186742-9de85400-a0f2-11ea-938c-09ade6680eff.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Chrome

**Comment by vikasrohit** [comment]
Should be fixed in dev now.

**Comment by vikasrohit** [comment]
@drasticdpk it can be verified on dev.

**Comment by drasticdpk** [comment]
Verified on Dev Env:
However in given requirement we have 11 stage, but current screen we have 12 stage. Please verify **review** stage is required or not? cc  @acshields .
![image](https://user-images.githubusercontent.com/25297859/84034103-9b6edf80-a9b9-11ea-8c62-b28d6b90c7c7.png)

**Comment by vikasrohit** [comment]
I think it is okay to have the phase. May the @acshields missed while preparing that list, the issue was about the order of the phases. If there is any missing phase or extra phase, we might log it in future as need arises.
