### ISSUE TITLE
Improve Edit Challenge Schedule link

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#668]
It is not intuitive as of now when we click on Edit link against the `Challenge Schedule` section. Because of caret icon it is giving experience of accordion which is okay but it can be avoided to reduce the confusion of what actually going to happen when is caret is up or down.
@acshields I would propose to use a simple Edit Timeline button (which may open the timeline editor in popup or we can have a dedicated page for editing the timeline).

**Comment by acshields** [comment]
@vikasrohit - this suggestion is in-line with the new UI designs I am partnering with Issa on. If the change is as simple as replacing the "edit" link with a button that says, "Edit Timeline," we can make that change now.

**Comment by vikasrohit** [comment]
Yes, my intention is to simple text change and remove the caret icon to avoid confusion. However, on a separate note, once user clicks on the edit button, right now there is no way to persist the changes that user made. In fact it does not update the Gantt chart view as well. It would require logging a separate issue (if not already) for handling the persistence of the changed phases/timeline.

**Comment by acshields** [comment]
Oh man, good catch. I hadn't observed that. That's a definite issue. Will log now and add to this milestone.

**Comment by vikasrohit** [comment]
Edited timeline is saved when user hits the global save button at the bottom.

**Comment by vikasrohit** [comment]
@drasticdpk I have tried to improve the experience around the editing of the phases within the limits of the current design.
@acshields Now it also has a dedicated button for saving the changes in phases only which was confusing earlier because we had `Reset Phases` button which resets the phases while for the updates in the phases, user has to click `Save as Draft` button. Now, the new button `Save Phases` won't update the challenge's status and will only persist the phases changes.

**Comment by drasticdpk** [comment]
Verified on dev env.
