### ISSUE TITLE
Challenges of a project are not listed while the challenge can be edited by deep link

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#670]
The challenges for the selected project are not listed even though we can edit a challenge of the same project if we have the deep link.

**Test Project**: 6640 "Test Connect app 2.4.4 Web UI testings"
**Challenge**: 32c3fd5f-3a3b-470e-a463-647899504b24

@acshields what do you suggest? What is the expectation here? Actual reason of project not being listed on list page is that it is filtering challenges based on logged in member's user id which does not match for me as the said challenge is created by you. So, it might be listing the challenge for you but not for any other user.

**Comment by acshields** [comment]
@vikasrohit re: our conversation today.

I think this is an important issue to resolve immediately after production release.

Initial things we will need to think through:

- On any project, all Topcoder or Copilot users who are joined to a Connect project should be able to see all created work (challenges/F2Fs/tasks) for the project.

- In the future, certain projects will also need to provide this visibility to client users as well.

**Comment by vikasrohit** [comment]
I think it is related to the #597

**Comment by vikasrohit** [comment]
For now, I have enabled listing of all challenges of the project without filtering via resources in challenges api as it seems to be a bug with challenge api topcoder-platform/challenge-api#147
