### ISSUE TITLE
Type Selection Options

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/challenge-engine-ui#672]
Re: conversation with James, the "Type" selections should be narrowed down to the following, regardless of track:

- Challenge

- First2Finish

- Assigned Task

However, I am still seeing a long list of challenge "types" available for selection in the dropdown menu.

**Comment by vikasrohit** [comment]
@acshields we need to discuss this before implementing because there is no corresponding legacy type for `Challenge` and I have no idea how things would work without a legacy type mapped to these new types.

**Comment by acshields** [comment]
Yep - we will need to pull in @rootelement to discuss. I believe there was some efforts underway with Thomas in the past with this issue, but I don't know where that is at.
