### ISSUE TITLE
Enable Chameleon in Production

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/challenge-engine-ui#674]
Immediately after the Work Manager is moved into production, we need to ensure that Chameleon is set-up in prod so that I can create tooltips & training content workflows for users.

Install this code snippet in the application: 

<script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var t=analytics.methods[e];analytics[t]=analytics.factory(t)}analytics.load=function(e,t){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src="https://cdn.segment.com/analytics.js/v1/"+e+"/analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(n,a);analytics._loadOptions=t};analytics.SNIPPET_VERSION="4.1.0";
  analytics.load("QSQAW5BWmZfLoKFNRgNKaqHvLDLJoGqF");
  analytics.page();
  }}();
</script>

**Comment by vikasrohit** [comment]
@acshields I have enabled the segment on production, please check if you can see chameleon working for you.

**Comment by vikasrohit** [comment]
@acshields closing the task assuming you are able to enable chameleon on production as well.
