### ISSUE TITLE
Adapt for terms data model change

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#679]
Terms data model is now updated to have following schema:
https://github.com/topcoder-platform/challenge-api/blob/b989fe78e1aa3fc05686e2fe6bd8376576d8dad0/src/services/ChallengeService.js#L541

We need to adapt the UI to prepare the parameter in the same format. However, how we are going to map the role with terms? Terms api only return terms with no association to roles. And when challenge creation UI is auto selecting the terms, which role it should pick for which terms?
For now assuming that mostly it is submitter for whom terms is applicable.

New changes in terms data structure are causing following error:
![image (1)](https://user-images.githubusercontent.com/2417632/83875490-cc020f80-a754-11ea-97c0-ab34c942ac92.png)

**Comment by drasticdpk** [comment]
@vikasrohit we are getting below issue while creating the new challenge.
reference 
![image](https://user-images.githubusercontent.com/25297859/84164485-4a7eea00-aa92-11ea-943e-ca95daad78d8.png)

**Comment by vikasrohit** [comment]
To close the loop on the last issue faced in https://github.com/topcoder-platform/challenge-engine-ui/issues/679#issuecomment-641355352, it seems it was a temporary issue, not occurring any more.

**Comment by drasticdpk** [comment]
Now it is working as expected. And closing it.
