### ISSUE TITLE
Console error when rendering the challenge timeline

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#682]
```
index.js:1437 Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    in ChallengeScheduleField (at ChallengeEditor/index.js:1081)
    in div (at ChallengeEditor/index.js:1031)
    in form (at ChallengeEditor/index.js:1030)
    in div (at ChallengeEditor/index.js:1132)
    in div (at ChallengeEditor/index.js:1129)
    in div (at ChallengeEditor/index.js:1125)
    in ChallengeEditor (created by Route)
    in Route (created by withRouter(ChallengeEditor))
    in withRouter(ChallengeEditor) (at ChallengeEditor/index.js:122)
    in Route (at ChallengeEditor/index.js:118)
    in div (at ChallengeEditor/index.js:96)
    in ChallengeEditor (created by Context.Consumer)
    in Connect(ChallengeEditor) (created by Route)
    in Route (created by withRouter(Connect(ChallengeEditor)))
    in withRouter(Connect(ChallengeEditor)) (at routes.js:78)
    in div (at TwoColsLayout/index.js:33)
    in Unknown (at App/index.js:13)
    in div (at TwoColsLayout/index.js:15)
    in TwoColsLayout (at App/index.js:9)
    in Route (at routes.js:75)
    in Switch (at routes.js:61)
    in Routes (created by Context.Consumer)
    in Connect(Routes) (created by Route)
    in Route (created by withRouter(Connect(Routes)))
    in withRouter(Connect(Routes)) (at App.js:14)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:13)
    in Provider (at App.js:12)
    in App (at src/index.js:10)
```
This error is appearing in console when the timeline is rendered on the page.

**Comment by vikasrohit** [comment]
It seems this issue is because of incorrect usage of `setState` method [here](https://github.com/topcoder-platform/challenge-engine-ui/pull/636/files#diff-2aeb73ee117eebf63b62dcf0f3c9c744R252). I have removed the method `renderTimelineAgain` to get rid of the error and verified that original [issue](https://github.com/topcoder-platform/challenge-engine-ui/issues/448) because of which this change was introduced, is not occurring as well.
In case, we are able to reproduce the original issue again, we would try to fix it with more elegant way than calling `setState` from `render` method.

**Comment by vikasrohit** [comment]
@drasticdpk can you please verify that the original [issue](https://github.com/topcoder-platform/challenge-engine-ui/issues/448) is not reproducible after this change? I mean there should not be a regression for that issue with this fix. Please note some steps of the original issue are changed as auto saving is disabled (via https://github.com/topcoder-platform/challenge-engine-ui/issues/659) for many of the fields.

**Comment by vikasrohit** [comment]
We can close this issue once verified, no need to keep it open for retesting.

**Comment by drasticdpk** [comment]
Verified accordingly. 
reference : https://monosnap.com/file/Xi2zmeaNjwcCFPoer4iDOL8eIrh7V7


> Given [information](https://github.com/topcoder-platform/challenge-engine-ui/wiki/Known-rules-facts-for-MVP-v1), Challenge Type to Timeline Template mapping is not implemented yet, so all challenges would be created with 'Standard Development' timeline template

But here after editing the challenge, always redirected to "**Marathon Match"**, please confirm this is due to current change or do I suppose to logged on separate issue. 
URL : https://challenges.topcoder-dev.com/projects/16529/challenges/0f6f2ebb-6fab-453e-a513-a369a744515e/view
![image](https://user-images.githubusercontent.com/25297859/83880390-c4dfff00-a75e-11ea-85a6-8de10cda6bd8.png)

**Comment by vikasrohit** [comment]
I double checked by checking out the git commit before my changes for this issue and it seems to be issue there as well i.e. I am seeing the `Marathan Match` for timeline template even without the changes for this issue. Please log a separate issue with bit more details there. I can see that `Task` timeline template is correctly shown when I created a challenge with `Code` type e.g. projects/16573/challenges/606d02cf-fe70-46ce-b4e5-4b433170afc6/view

**Comment by drasticdpk** [comment]
Ok noted @vikasrohit
