### ISSUE TITLE
Status field is not present when editing a challenge

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#683]
Status is present in read only view but not in edit challenge screen.

<img width="1156" alt="Screen Shot 2020-06-09 at 8 26 48 PM" src="https://user-images.githubusercontent.com/2417632/84163891-95e3c900-aa8f-11ea-99ad-6514f9f826e5.png">

**Comment by drasticdpk** [comment]
@vikasrohit I will highly appreciate if you upload some reference image too. It will easy for understand and verification the issue.
![image](https://user-images.githubusercontent.com/25297859/84160324-c460a480-aa8d-11ea-9a42-8c7c778dd293.png)

Note here we can see some field are unable to load, it will crate separate issue for them (eg. Type)
