### ISSUE TITLE
Always taking Marathon Match as Timeline Template while updating challenge. 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/challenge-engine-ui#685]
1. Create new challenge {Track : Development, Type : Code}
2. Timeline Template : Task
3. Go to edit and Update some other information ( eg. Challenge Schedule) 
4. Go to challenge details and observe Timeline Template.

Actual Result : Timeline Template has updated to Marathon Match
Expected Result : There should be same Timeline Template which was selected by User not Marathon Match 
Reference video : https://monosnap.com/file/Xi2zmeaNjwcCFPoer4iDOL8eIrh7V7

Developer Note : Please confirm for all challenge Type (Development, Design, Data Science and QA)

**Comment by vikasrohit** [comment]
@acshields for now I am moving it v2 of MVP, please feel free to relocate it as per needs.

**Comment by drasticdpk** [comment]
Verified on Dev Env
![image](https://user-images.githubusercontent.com/25297859/84345361-e44ab200-abcc-11ea-947f-cb4d5a9318ba.png)
Time -line template is loading based on selected challenge track type.
https://api.topcoder-dev.com/v5/challenge-timelines?page=1&perPage=100
