### ISSUE TITLE
New challenge page keeps loading forever

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-engine-ui#686]
I'm trying to create a challenge using the following link https://challenges.topcoder-dev.com/projects/16531/challenges/new but the page keeps loading forever without any errors in the console.

I'm logged in as `jcori` but also tried with the `TonyJ` account.

<img width="1792" alt="Screenshot 2020-06-09 at 2 35 40 PM" src="https://user-images.githubusercontent.com/4612921/84143018-826c3a00-aa5e-11ea-882c-4a97905427e3.png">

This is blocking my testing of the processors (https://github.com/topcoder-platform/challenge-api/issues/150).

cc @rootelement

**Comment by vikasrohit** [comment]
@ThomasKranitsas Yep, @drasticdpk raised the issue few hours ago. I have logged it here #687. fyi, just applied a fix for it, should be on dev in 15 minutes.

**Comment by drasticdpk** [comment]
With reference to above discussion , I am closing this issue , Please let us know for anythig.
