### ISSUE TITLE
New challenge screen is loading for ever

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#687]
It is never stopping loading.

![image (1)](https://user-images.githubusercontent.com/2417632/84149787-a2135a80-aa7e-11ea-904b-d33a208e76f9.png)

**Comment by vikasrohit** [comment]
reason is that `v5/chalenge-phases` endpoint returning empty phases array now while it is still returning the specific phases by id. It seems like something paging related has changed in the api which caused explicit specification of paging params. So, passing `page` and `perPage` params, fixes the issue.

**Comment by drasticdpk** [comment]
Verified on Dev env.
![image](https://user-images.githubusercontent.com/25297859/84157845-ead11080-aa8a-11ea-945e-50a30a82ee83.png)
