### ISSUE TITLE
 Timeline template missing on Challenge Edit window.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/challenge-engine-ui#688]
1. Go to Challenge edit window and observe the Timeline template field.
![image](https://user-images.githubusercontent.com/25297859/84168547-40131f00-aa97-11ea-95bc-935476655c16.png)

**Comment by vikasrohit** [comment]
Fixed and deployed to dev.

**Comment by drasticdpk** [comment]
Verified on Dev Env
![image](https://user-images.githubusercontent.com/25297859/84226460-84d3a000-ab01-11ea-9013-b4939406cbb2.png)
