### ISSUE TITLE
Saving a challenge sets the legacyId to null

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-engine-ui#689]
I just tried to edit https://challenges.topcoder-dev.com/projects/16531/challenges/14cecae1-2646-43be-8804-d9f4cd668f05/edit and it set the `legacyId` to `null`.

The `legacyId` was previously populated by the legacy processor

cc @rootelement

**Comment by vikasrohit** [comment]
@ThomasKranitsas is it still happening for you? If yes, I think it is happening because of the root cause of another issue mentioned here https://github.com/topcoder-platform/challenge-api/issues/198#issuecomment-652995848

**Comment by vikasrohit** [comment]
@acshields Brining it back from Backlog to keep an eye on it.

**Comment by vikasrohit** [comment]
@drasticdpk can you please check if it is happening for you?

**Comment by vikasrohit** [comment]
Closing as it not reproducing now. @ThomasKranitsas please feel free to reopen if you are still seeing the issue.

**Comment by vikasrohit** [comment]
@drasticdpk @codejamtc it would be great if we can verify it once before closing.

**Comment by codejamtc** [comment]
@vikasrohit When editing a challenge I can see the `Direct` and `OR` links are working

**Comment by drasticdpk** [comment]
Withe reference to team discussion closing this issue.
