### ISSUE TITLE
No way to set the Task submitter resource

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-engine-ui#692]
There should be a way to set the `Submitter` resource for a challenge of type `TASK`

**Comment by ThomasKranitsas** [comment]
For example, a search field should show up and it should allow the copilot to search members using their handles.

It should also allow changing the Submitter (removing the old one and adding a new one)

**Comment by vikasrohit** [comment]
Yep, we have it logged already #673. Marking it as duplicate, @ThomasKranitsas please feel free to reopen if I miss understood the issue.
