### ISSUE TITLE
Prizes are not being passed correctly

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-engine-ui#694]
1. Login as `jcori`
2. Create a new challenge of type Task
3. Set all required fields and save as Draft
4. Refresh

### Actual behavior
The prize is reset to `0`

### Expected behavior
The prize should remain as the one I set earlier ($50 in my case)

As you can see here https://api.topcoder-dev.com/v5/challenges/d34684eb-cdc9-43c6-a2b4-435b700f1101 the prize is `0` even though I had set it to 50.

```
"prizeSets": [
        {
          "type": "placement",
          "prizes": [
            {
              "type": "money",
              "value" [1]: "0"
            }
          ]
        }
      ]
```

**Comment by drasticdpk** [comment]
Hi @ThomasKranitsas ,
1. I am unable to replicate issue  as mentioned above steps. May I know how you did Refresh?
2. Response format also different for prizeSets, please confirm.
![image](https://user-images.githubusercontent.com/25297859/84800754-f6d64880-b01d-11ea-8231-e70c5fa6119d.png)

Reference API :https://api.topcoder-dev.com/v5/challenges/a6467f63-b0d0-4a2e-9455-27ea7bcd83ea

**Comment by vikasrohit** [comment]
Thanks @drasticdpk for being proactive here and for your investigation.

@ThomasKranitsas let us know what we are missing here to reproduce the issue.

**Comment by vikasrohit** [comment]
Keeping it in first release milestone assuming that failing this issue is causing issue in creating legacy challenge in legacy processor. @ThomasKranitsas correct me if I am wrong here about its impact on legacy processor.

**Comment by ThomasKranitsas** [comment]
As you can see here http://api.topcoder-dev.com/v5/challenges/afb220ff-3cbf-4c96-861a-638206919473 the CM adds a default prize of $0 for a newly created challenge. I haven't edited anything there. The CM should not add a default prize. It should create the challenge with only the projectId, name, typeId and the track. It should not add default values for anything else.

cc @rootelement

**Comment by vikasrohit** [comment]
Okay, I guess then we need to update the original issue description to say about problem with default values of prizes field, right @ThomasKranitsas? Do you think it is needed to be fixed in first release?

**Comment by vikasrohit** [comment]
@ThomasKranitsas Should we keep the prizeSets to null or just not pass the prizeSets at all?

**Comment by drasticdpk** [comment]
Verified.
Does not have prizeSets of challenge when  status is **New**
https://api.topcoder-dev.com/v5/challenges/9adb5054-3f40-487f-ada8-801efd9437b8
![image](https://user-images.githubusercontent.com/25297859/86905389-b86e0e00-c131-11ea-8829-b6bd74bc615d.png)
![image](https://user-images.githubusercontent.com/25297859/86905693-2adeee00-c132-11ea-9d3b-53be4c7e5e84.png)
