### ISSUE TITLE
All projects are not listing 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/challenge-engine-ui#702]
**To Reproduce / Actual Behavior**

1. Go to 'https://challenges.topcoder-dev.com/' 
2. Go to project list and observe. Only 20 project are listed.

**Expected behavior**
All project should be loaded (with either pagination or page scroll/load more button etc) 

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/25297859/84934491-1a20f680-b0f7-11ea-89b7-fedbaac9b917.png)
![image](https://user-images.githubusercontent.com/25297859/84934697-6d934480-b0f7-11ea-8280-d2ced7b3f8cd.png)
**User** :  TonyJ

**Comment by vikasrohit** [comment]
@drasticdpk to give you some more context, the app is not meant to be project manager and it is mostly used in tandem with Connect (which is in fact a project manager app). This app is assumed to be working always in context of a project and we are providing list of projects, on page load, as a starting place for new users and we can not add every feature that we need for searching/navigating projects. So, we just need basic functionality of searching projects here. As I noted in the wiki, user can search project by id, which serves the use case of setting a project context for the app.
