### ISSUE TITLE
Disable editing timeline template for a challenge

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#706]
As per discussions around https://github.com/topcoder-platform/challenge-api/issues/199, we need to disable the feature of selecting and editing timeline for a v5 challenge.

**Comment by vikasrohit** [comment]
fyi @drasticdpk @lakshmiathreya @acshields

**Comment by drasticdpk** [comment]
Hi @vikasrohit ,
> Temporarily, disable the ability to change the timeline template on a challenge if the status is not New.

Above desc, asking to disable  timeline template for other than New status. Here we could not find ability to change the timeline for status New too. Can you please confirm ?

Reference :

![image](https://user-images.githubusercontent.com/25297859/86367278-765d4c00-bc9b-11ea-9eb0-ef72f2dab243.png)

**Comment by vikasrohit** [comment]
I can confirm that we don't have ability to change/update timeline of even a New challenge. So, I have disabled it UI for all status though API still allows updating the timeline for New challenges. The way legacy processor is written as of now, can not use the timeline of v5 challenge to update or set the v4 challenge timeline.
fyi @rootelement @ThomasKranitsas

**Comment by drasticdpk** [comment]
Ok noted @vikasrohit
