### ISSUE TITLE
New Challenge - Back button should take user to Challenge listing

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#707]
The back button on the New Challenge page should take user to Challenge listing page, however, as of now it taking user to the root of the application.

![BackButtonOnNewChallengePage](https://user-images.githubusercontent.com/2417632/86084318-2bd0a980-baba-11ea-8fb9-f8f519973468.gif)

**Comment by drasticdpk** [comment]
Verified on Dev env
Reference :
![image](https://user-images.githubusercontent.com/25297859/86365597-6f353e80-bc99-11ea-8609-e4ccba27020a.png)
![image](https://user-images.githubusercontent.com/25297859/86365666-86742c00-bc99-11ea-85a2-16786a8d8826.png)
