### ISSUE TITLE
Type of an old project is not shown, if we deprecated that type later on

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#709]
During the development and testing of challenge api and challenge manager, we changed supported challenge types many times and it is quite possible that we would get the similar situation in future as well, where we are going to deprecate some type and introduce new ones.
Challenge Manager, as of now is unable to show the type of such challenge if that type is deprecated e.g. project `8e1be511-ce4d-4425-8601-04387550aadf`.
<img width="840" alt="Screen Shot 2020-06-30 at 3 06 46 PM" src="https://user-images.githubusercontent.com/2417632/86110551-53883780-bae3-11ea-93af-223940a79db1.png">

**Comment by vikasrohit** [comment]
fyi @drasticdpk

**Comment by drasticdpk** [comment]
Verified on Dev env.
![image](https://user-images.githubusercontent.com/25297859/86365240-f8984100-bc98-11ea-94cf-49562fa3cd81.png)
