### ISSUE TITLE
Update Reviewer Q&A Copy and Answer Format

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/challenge-engine-ui#722]
**Current Version:** 
- Question Title: Review Type
- Answer Format: Radio Buttons [Community/Internal]

**Desired Updates:**
- Question Title: Reviewer
- Answer Format: Toggle Button [Community/Internal]
Answer Logic: Default to Community.

**Comment by vikasrohit** [comment]
@acshields we don't yet have a UI component for Toggle Button, hence I have kept it as radio button but I have updated the copy as suggested.
