### ISSUE TITLE
Update Button Copy to Read "Continue Set-Up"

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/challenge-engine-ui#727]
**Current Version:** On Screen 1 of challenge set-up, the button at the bottom reads: "Create Challenge"
<img width="707" alt="Screen Shot 2020-07-16 at 5 43 21 PM" src="https://user-images.githubusercontent.com/41118149/87729831-de2b9080-c78b-11ea-880b-a92ee1a194ee.png">

**Desired Update:** On Screen 1 of challenge set-up, update the button to read: "Continue Set-Up"

_Note: As some clients will be engaging with this application in the future, we want to use the term "work" where appropriate because it is more agnostic than challenge, which has specific implications to clients (challenge = competition vs. assigned task = no challenge, for example)._

**Comment by vikasrohit** [comment]
@acshields just want to let you know that challenge is actually created after user hits this button, just in case that requires rethinking for button name change. At least to me `Continue set-up` means something is not created yet but would be created after I finish more setup of the same.
