### ISSUE TITLE
Handle recent changes in terms api

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#728]
Terms api is updated as per https://github.com/topcoder-platform/terms-service/issues/30

We need to update to comply with the changes.

fyi @mtwomey @acshields

**Comment by vikasrohit** [comment]
We didn't need fix in challenge manager, rather it was taken care at challenge api.

**Comment by acshields** [comment]
@vikasrohit - Noted! Thanks.
