### ISSUE TITLE
Set-Up Screen 1 Q&A Copy Updates

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/challenge-engine-ui#734]
### Screen 1 Q&A Copy Updates
- **Question 1 Relabel:** Work Type 
- **Q1 Answer Options:** No Changes [Buttons - Design/Development/QA/Data Science]

- **Question 2 Relabel:** Work Format
- **Q2 Answers:** Relabel Dropdown Menu Options
-Challenge
-First 2 Finish Task
-Assigned Task

- **Question 3 Relabel:** Work Name
- **Q3 Answer:** No Changes [Text Entry]

<img width="956" alt="Screen Shot 2020-07-17 at 10 08 14 AM" src="https://user-images.githubusercontent.com/41118149/87801527-7752b980-c815-11ea-8da0-7fbcd9671a09.png">

**Comment by vikasrohit** [comment]
@acshields I have done all copy changes except renaming the type options because those are to be done in database and I am not sure if everything works after renaming them. So, I am testing it for now and once I know that it is not affecting the functionality, I would update the databases.
