### ISSUE TITLE
Adapt ChallengeManager for recent refactoring in challenge api

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#744]
There has been another major refactoring in challenges api (https://github.com/topcoder-platform/challenge-api/issues/242) to improve the overall stability of the api and we need to adapt the UI for the same.

**Comment by drasticdpk** [comment]
With reference to task details ( it is more related to API side), I updated status, Please let me know  for anything.

**Comment by vikasrohit** [comment]
Yep, nothing else needed. Closing it right away, we don't need to carry this one until release.
