### ISSUE TITLE
Invalid search result displayed when search a project via any text

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#787]
[11.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5158934/11.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Type 'ok' on the Switch project textbox
4. Check the result (Ok, qq)
5. Click on the Project:qq and check any text related to Ok

### Actual behavior
- Invalid search result displayed when searching a project via any text

### Expected behavior
- Should display the projects that have the search term inside the project

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
@codejamtc I think search is working as expected. It searches for anything with the text. I can random text in the description of project qq and that random text has ok multiple times.
