### ISSUE TITLE
Some details are not carried to the Direct

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#795]
[12.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5170709/12.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Create a Project with Copilot, Copilot Fee, NDA etc - https://challenges.topcoder-dev.com/projects/16604/challenges/e0ee3f7c-7de5-4ff1-977a-169dc4fa7e1f/view
4. Go to Direct and open the same challenge
5. Check the details https://www.topcoder-dev.com/direct/projectOverview.action?formData.projectId=23642

### Actual behavior
- Some details are not carried to the Direct

### Expected behavior
- Should display the data in Direct also

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
@codejamtc can you please explicitly mention in the ticket which all fields are missing in the sync?

**Comment by codejamtc** [comment]
@vikasrohit 

- https://challenges.topcoder-dev.com/projects/16604/challenges/7f5f2fe6-b9ff-4def-bd44-5de0713ae806/view
- https://www.topcoder-dev.com/direct/contest/detail?projectId=30057030

**Missing**

- NDA is
- Copilot
- Assign Member(s)
- Copilot Fee

[1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5196723/1.zip)

**Comment by rootelement** [comment]
This should be fixed and deployed. Please reopen if not.
