### ISSUE TITLE
After creating a challenge and save it as a draft won't display the challenge on the draft

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#808]
[1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5219644/1.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder.com/ and login as codejam
2. Select a project from the list 'Q2: Customer Experience Prod/Dev Delivery (Connect Projects)'
3. Create a challenge with Copilot (codejam), Copilot Fee, NDA etc
4. Wait 1 min 
5. Go to Draft tab and check

```
xhr.js:175 GET https://api.topcoder.com/v5/terms?page=1&perPage=10 403
(anonymous) @ xhr.js:175
e.exports @ xhr.js:18
e.exports @ dispatchRequest.js:39
Promise.then (async)
u.request @ Axios.js:64
u.<computed> @ Axios.js:79
(anonymous) @ bind.js:11
(anonymous) @ challenges.js:177
x @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
ca @ challenges.js:175
la @ challenges.js:175
(anonymous) @ challenges.js:318
x @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ challenges.js:317
(anonymous) @ index.js:8
(anonymous) @ redux.js:478
value @ index.js:49
us @ react-dom.production.min.js:5161
(anonymous) @ react-dom.production.min.js:6408
t.unstable_runWithPriority @ scheduler.production.min.js:309
qo @ react-dom.production.min.js:2816
_u @ react-dom.production.min.js:6204
lu @ react-dom.production.min.js:5895
(anonymous) @ react-dom.production.min.js:2851
t.unstable_runWithPriority @ scheduler.production.min.js:309
qo @ react-dom.production.min.js:2816
$o @ react-dom.production.min.js:2846
Ko @ react-dom.production.min.js:2836
N @ react-dom.production.min.js:7265
(anonymous) @ react-dom.production.min.js:1329
Show 11 more frames
11:02:14.328 createError.js:17 Uncaught (in promise) Error: Request failed with status code 403
    at e.exports (createError.js:17)
    at e.exports (settle.js:19)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:63)
```

### Actual behavior
- After creating a challenge and save it as a draft won't display the challenge on the draft

### Expected behavior
- Should display on the draft tab

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `codejam`

**Comment by lakshmiathreya** [comment]
Able to create only via Admin role 
<img width="1477" alt="Screenshot 2020-09-14 at 11 48 51 PM" src="https://user-images.githubusercontent.com/51733042/93122874-e26d1f00-f6e4-11ea-952d-825023fa728d.png">

**Comment by codejamtc** [comment]
@vikasrohit I tested the Dev using my own copilot account. I can create challenges and I can see them on the draft tab

today I can create and see the challenges created on prod too

**Comment by vikasrohit** [comment]
Okay, so what is the status of the issue on prod now? I mean is it still there or is it fixed now?

**Comment by codejamtc** [comment]
@vikasrohit I can create challenges and save them as a draft

**Comment by vikasrohit** [comment]
so we can close it, right? I mean this issue happen temporarily only on one particular day, so we can close it if it is not happening now.

**Comment by codejamtc** [comment]
@vikasrohit Yes, I will mark this ticket as `QA Pass` for now; If I encounter anything I will open a separate ticket
