### ISSUE TITLE
Challenge Phase Does not Sync.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/challenge-engine-ui#815]
**Steps**
1. Create new challenge from WM and launch it.
2. Observe the phase between WM app and  Challenge Listing page.

**Reference**
![image](https://user-images.githubusercontent.com/25297859/93362989-5f73d200-f866-11ea-963f-43dc87c2ae3d.png)

**Comment by vikasrohit** [comment]
Duplicate https://github.com/topcoder-platform/challenge-engine-ui/issues/802
