### ISSUE TITLE
Empty 'Public specification' is saved even thoguh the user gets a validation while saving without the spec

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#855]
[6.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5325782/6.zip)

### Steps to reproduce the problem

URL: https://challenges.topcoder-dev.com/projects/16604/challenges/6d3df1a6-3658-4c7a-8bb2-474e71fde0ee/edit

1. Open https://challenges.topcoder-dev.com/ and login as Copilot
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Create a Dev challenge
4. Fill all the mandatory details and Click Save as draft
5. Click Edit
6. Remove the 'Public specification' and Click Save as draft
7. Click Back
8. Open the same challenge and check the 'Public specification'

### Actual behavior
- Empty 'Public specification' is saved even thoguh the user gets a validation while saving without the spec

### Expected behavior
- Should not save the changes

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `TCConnCopilot`

**Comment by vikasrohit** [comment]
@codejamtc I remember this one being reported earlier, though I am able to find the old one. I think we had very specific discussion around this @codejamtc.

**Comment by codejamtc** [comment]
@vikasrohit https://github.com/topcoder-platform/challenge-engine-ui/issues/778

**Comment by vikasrohit** [comment]
Thanks @codejamtc, do you still want to keep this one? I mean if you want to highlight different issue than #778, please let me know, otherwise we can close this one.
