### ISSUE TITLE
Trying to save a challenge as a draft, but without all required information silently fails

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/challenge-engine-ui#866]
When you try this - the save as draft button just doesn't do anything. There should be a error or something directing the user to provide that missing information.

**Comment by vikasrohit** [comment]
We have this one logged https://github.com/topcoder-platform/challenge-engine-ui/issues/848 and kept it for next release as IMO it is a negative test case and our first set of audience is not going to do this practically.
