### ISSUE TITLE
Manage challenge resources

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-engine-ui#87]
When we create/update a challenge, we should manage the following resources:
- Challenge copilot (if selected)
- Reviewer (if the review type is set to internal)
- Observers (all members that have access to the same group. Maybe filtered by roles?)
- Manager (similar to Observers but with write access. Filtered by roles)

The review role IDs should be configurable.

**Comment by ThomasKranitsas** [comment]
@cwdcwd thoughts on this?

**Comment by cwdcwd** [comment]
we could probably push that to a processor instead of coding it into the API
